# --- Performa Animasi ---
backend = "glx";
vsync = true;

# --- Sudut Melengkung (Rounded Corners) ---
corner-radius = 12;
round-borders = 1;
detect-rounded-corners = true;

# --- Efek Cyberpunk Glow (Bayangan Ungu Neon) ---
shadow = true;
shadow-radius = 20;
shadow-offset-x = -20;
shadow-offset-y = -20;
shadow-opacity = 0.85;
shadow-color = "#b300ff";  # Kode warna ungu neon

# Pengecualian agar bar bawah (i3bar) tidak ikut melengkung/bersinar aneh
shadow-exclude = [
    "class_g = 'i3-frame'",
    "class_g = 'i3bar'"
];
rounded-corners-exclude = [
    "class_g = 'i3bar'",
    "window_type = 'dock'",
  "window_type = 'desktop'"
];

# --- Animasi Fading (Transisi Mulus) ---
fading = true;
fade-delta = 5;
fade-in-step = 0.03;
fade-out-step = 0.03;

# --- Transparansi Jendela Tak Aktif ---
inactive-opacity = 0.90;
active-opacity = 1.0;
frame-opacity = 1.0;

# --- Aktifkan Animasi ---
animations = true;
animation-window-mass = 0.5;
animation-stiffness = 350;
animation-damping = 25;
animation-clamping = true;

# Atur gaya animasi buka/tutup jendela
animation-for-open-window = "zoom";
animation-for-unmap-window = "zoom";
animation-for-workspace-switch-in = "zoom";
animation-for-workspace-switch-out = "zoom";
