# Warna latar hitam pekat dan sedikit transparan (85%)
background #000000
background_opacity 0.85

# Menghilangkan suara notifikasi "beep" yang mengganggu
enable_audio_bell no

# Margin dalam agar teks tidak terlalu menempel ke pinggir
window_padding_width 10

font_family      JetBrainsMono Nerd Font
font_size        12.0

# --- Konfigurasi Kursor Cyberpunk ---
cursor_shape beam
cursor_blink_interval 0.5 ease-in-out
cursor_stop_blinking_after 0
cursor_trail 3
